# platform :ios, '13.0'

target 'Hola Frogger' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hola Frogger
  pod 'iOSDropDown'
  pod 'lottie-ios'
  pod 'AwesomeSpotlightView'

end
