# platform :ios, '13.0'

target 'TabView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TabView
  pod 'RAMReel'
  pod 'iOSDropDown'
  pod 'lottie-ios'
  pod 'AwesomeSpotlightView'

end
